export  const userData = [
  {
    firstname: "Alice",
    lastname: "Johnson",
    email: "alice.johnson@example.com",
    role: "admin",
    lastLogin: "2025-01-10T09:15:00Z",
    Active: true,
  },
  {
    firstname: "Bob",
    lastname: "Miller",
    email: "bob.miller@example.com",
    role: "user",
    lastLogin: "2025-01-11T12:22:00Z",
    Active: false,
  },
  {
    firstname: "Carol",
    lastname: "Nguyen",
    email: "carol.nguyen@example.com",
    role: "readonly",
    lastLogin: "2025-01-12T14:50:00Z",
    Active: true,
  },
  {
    firstname: "David",
    lastname: "Smith",
    email: "david.smith@example.com",
    role: "user",
    lastLogin: "2025-01-13T11:05:00Z",
    Active: false,
  },
  {
    firstname: "Eva",
    lastname: "Lopez",
    email: "eva.lopez@example.com",
    role: "admin",
    lastLogin: "2025-01-14T08:33:00Z",
    Active: true,
  },
  {
    firstname: "Frank",
    lastname: "Garcia",
    email: "frank.garcia@example.com",
    role: "user",
    lastLogin: "2025-01-15T13:10:00Z",
    Active: false,
  },
  {
    firstname: "Grace",
    lastname: "Kim",
    email: "grace.kim@example.com",
    role: "readonly",
    lastLogin: "2025-01-16T17:45:00Z",
    Active: true,
  },
  {
    firstname: "Henry",
    lastname: "Adams",
    email: "henry.adams@example.com",
    role: "readonly",
    lastLogin: "2025-01-17T07:55:00Z",
    Active: false,
  },
  {
    firstname: "Ivy",
    lastname: "Bennett",
    email: "ivy.bennett@example.com",
    role: "user",
    lastLogin: "2025-01-18T10:22:00Z",
    Active: true,
  },
  {
    firstname: "Jack",
    lastname: "Turner",
    email: "jack.turner@example.com",
    role: "readonly",
    lastLogin: "2025-01-19T16:40:00Z",
    Active: false,
  },
];
