export const cloudAccountsData = [
  {
    accountName: "1MG - Prod",
    accountId: "111111111111",
    resourceName: "EC2-Prod-01",
    serviceType: "EC2",
    platform: "Linux",
    instanceType: "t3.medium",
    active: true,
  },
  {
    accountName: "1MG - Dev",
    accountId: "111111111112",
    resourceName: "RDS-Dev-01",
    serviceType: "RDS",
    platform: "PostgreSQL",
    instanceType: "db.t3.small",
    active: true,
  },
  {
    accountName: "1MG - QA",
    accountId: "111111111113",
    resourceName: "S3-QA-Bucket",
    serviceType: "S3",
    platform: "N/A",
    instanceType: "N/A",
    active: false,
  },
  {
    accountName: "2MG - Prod",
    accountId: "222222222221",
    resourceName: "Lambda-Prod-01",
    serviceType: "Lambda",
    platform: "Node.js",
    instanceType: "N/A",
    active: true,
  },
  {
    accountName: "2MG - Dev",
    accountId: "222222222222",
    resourceName: "EC2-Dev-01",
    serviceType: "EC2",
    platform: "Windows",
    instanceType: "t3.large",
    active: false,
  },
  {
    accountName: "2MG - QA",
    accountId: "222222222223",
    resourceName: "DynamoDB-QA-01",
    serviceType: "DynamoDB",
    platform: "N/A",
    instanceType: "N/A",
    active: true,
  },
  {
    accountName: "3MG - Prod",
    accountId: "333333333331",
    resourceName: "EKS-Prod-01",
    serviceType: "EKS",
    platform: "Linux",
    instanceType: "m5.large",
    active: true,
  },
  {
    accountName: "3MG - Dev",
    accountId: "333333333332",
    resourceName: "S3-Dev-Bucket",
    serviceType: "S3",
    platform: "N/A",
    instanceType: "N/A",
    active: true,
  },
  {
    accountName: "3MG - QA",
    accountId: "333333333333",
    resourceName: "EC2-QA-01",
    serviceType: "EC2",
    platform: "Linux",
    instanceType: "t3.micro",
    active: false,
  },
  {
    accountName: "3MG - Prod",
    accountId: "333333333334",
    resourceName: "RDS-Prod-01",
    serviceType: "RDS",
    platform: "MySQL",
    instanceType: "db.m5.large",
    active: true,
  },
];
