const ASGdata = [
  {
    resourceId: "asg-frontend-01",
    resourceName: "ASG-Frontend",
    region: "us-east-1",
    desiredCapacity: 3,
    minSize: 1,
    maxSize: 5,
    status: "Active",
  },
  {
    resourceId: "asg-backend-02",
    resourceName: "ASG-Backend",
    region: "us-west-2",
    desiredCapacity: 5,
    minSize: 2,
    maxSize: 8,
    status: "Active",
  },
  {
    resourceId: "asg-batch-03",
    resourceName: "ASG-Batch-Jobs",
    region: "ap-south-1",
    desiredCapacity: 2,
    minSize: 0,
    maxSize: 4,
    status: "Stopped",
  },
  {
    resourceId: "asg-analytics-04",
    resourceName: "ASG-Analytics",
    region: "eu-west-1",
    desiredCapacity: 6,
    minSize: 3,
    maxSize: 10,
    status: "Active",
  },
  {
    resourceId: "asg-frontend-test-05",
    resourceName: "ASG-Frontend-Test",
    region: "us-east-2",
    desiredCapacity: 1,
    minSize: 1,
    maxSize: 2,
    status: "Inactive",
  },
  {
    resourceId: "asg-orders-06",
    resourceName: "ASG-Orders",
    region: "eu-central-1",
    desiredCapacity: 4,
    minSize: 2,
    maxSize: 6,
    status: "Active",
  },
  {
    resourceId: "asg-monitoring-07",
    resourceName: "ASG-Monitoring",
    region: "ca-central-1",
    desiredCapacity: 2,
    minSize: 1,
    maxSize: 3,
    status: "Active",
  },
  {
    resourceId: "asg-payments-08",
    resourceName: "ASG-Payments",
    region: "ap-northeast-1",
    desiredCapacity: 5,
    minSize: 3,
    maxSize: 7,
    status: "Active",
  },
  {
    resourceId: "asg-internal-tools-09",
    resourceName: "ASG-Internal-Tools",
    region: "us-west-1",
    desiredCapacity: 1,
    minSize: 0,
    maxSize: 2,
    status: "Stopped",
  },
  {
    resourceId: "asg-ml-jobs-10",
    resourceName: "ASG-ML-Jobs",
    region: "ap-southeast-1",
    desiredCapacity: 8,
    minSize: 4,
    maxSize: 12,
    status: "Active",
  },
];

export default ASGdata;
