    const EC2data = [
    {
        accountId: "123456789012",
        resourceId: "i-0a1b2c3d4e5f6g1",
        resourceName: "EC2-Web-Server-1",
        region: "us-east-1",
        status: "Running",
        potentialSaving: "$25/month",
        schedulerEnabled: "Yes",
    },
    {
        accountId: "123456789012",
        resourceId: "i-0a1b2c3d4e5f6g2",
        resourceName: "EC2-App-Server",
        region: "us-west-2",
        status: "Stopped",
        potentialSaving: "$40/month",
        schedulerEnabled: "No",
    },
    {
        accountId: "234567890123",
        resourceId: "db-ABC123XYZ",
        resourceName: "RDS-User-DB",
        region: "eu-west-1",
        status: "Available",
        potentialSaving: "$60/month",
        schedulerEnabled: "Yes",
    },
    {
        accountId: "234567890123",
        resourceId: "i-0a1b2c3d4e5f6g3",
        resourceName: "EC2-Batch-Job",
        region: "ap-south-1",
        status: "Stopped",
        potentialSaving: "$30/month",
        schedulerEnabled: "Yes",
    },
    {
        accountId: "345678901234",
        resourceId: "db-XYZ789LMN",
        resourceName: "RDS-Orders",
        region: "us-east-2",
        status: "Available",
        potentialSaving: "$75/month",
        schedulerEnabled: "No",
    },
    {
        accountId: "345678901234",
        resourceId: "asg-frontend-01",
        resourceName: "ASG-Frontend",
        region: "us-west-1",
        status: "Active",
        potentialSaving: "$90/month",
        schedulerEnabled: "Yes",
    },
    {
        accountId: "456789012345",
        resourceId: "i-0a1b2c3d4e5f6g4",
        resourceName: "EC2-Test-Server",
        region: "ca-central-1",
        status: "Running",
        potentialSaving: "$20/month",
        schedulerEnabled: "No",
    },
    {
        accountId: "456789012345",
        resourceId: "asg-backend-02",
        resourceName: "ASG-Backend",
        region: "eu-central-1",
        status: "Active",
        potentialSaving: "$110/month",
        schedulerEnabled: "Yes",
    },
    {
        accountId: "567890123456",
        resourceId: "db-TEST456",
        resourceName: "RDS-Test-DB",
        region: "ap-northeast-1",
        status: "Stopped",
        potentialSaving: "$50/month",
        schedulerEnabled: "Yes",
    },
    {
        accountId: "567890123456",
        resourceId: "i-0a1b2c3d4e5f6g5",
        resourceName: "EC2-Analytics",
        region: "us-east-1",
        status: "Running",
        potentialSaving: "$85/month",
        schedulerEnabled: "No",
    },
    ];

    export default EC2data;
