// export const costExplorerData = {
//   labels: ["Jun 2025", "Jul 2025", "Aug 2025", "Sep 2025", "Oct 2025", "Nov 2025"],
//   datasets: [
//     { label: "EC2", data: [36000, 40000, 35000, 37000, 33000, 30000], backgroundColor: "#2B98FB" },
//     { label: "Savings Plans", data: [24000, 25000, 26000, 24000, 25000, 24000], backgroundColor: "#76DDFB" },
//     { label: "RDS", data: [25000, 24000, 24000, 25000, 24000, 23000], backgroundColor: "#FF9F22" },
//     { label: "Marketplace", data: [13000, 20000, 28000, 24000, 13000, 26000], backgroundColor: "#A8E03F" },
//     // { label: "Others", data: [50000, 48000, 42000, 36000, 40000, 37000], backgroundColor: "#facc15" },

//     { label: "Lambda", data: [8000, 9000, 8500, 8700, 8200, 7800], backgroundColor: "#a855f7" },
//     { label: "S3", data: [12000, 14000, 13500, 13000, 12500, 12800], backgroundColor: "#0ea5e9" },
//     { label: "CloudWatch", data: [6000, 6500, 7000, 6800, 6600, 6400], backgroundColor: "#14b8a6" },
//     { label: "EKS", data: [22000, 23000, 22500, 23500, 22800, 22000], backgroundColor: "#A8E03F" },
//     { label: "DynamoDB", data: [15000, 16000, 15500, 15800, 15200, 14900], backgroundColor: "#22c55e" },
//     { label: "CloudFront", data: [9000, 9500, 10000, 9800, 9700, 9600], backgroundColor: "#eab308" },
//     { label: "SNS", data: [3000, 3200, 3100, 3300, 3250, 3150], backgroundColor: "#6366f1" },
//     { label: "SQS", data: [4000, 4200, 4100, 4300, 4250, 4150], backgroundColor: "#ec4899" },
//     { label: "Elastic IP", data: [2000, 2100, 2050, 2150, 2120, 2080], backgroundColor: "#f97316" },
//     { label: "Route 53", data: [5000, 5200, 5100, 5300, 5250, 5150], backgroundColor: "#84cc16" },
//   ],
// };



export const snowflakeData = [
    {
        "ID": 1,
        "BILL_DATE": "2024-12-31T18:30:00.000Z",
        "SERVICE": "Amazon EC2",
        "INSTANCE_TYPE": "t3.medium",
        "ACCOUNT_ID": "123456789012",
        "USAGE_TYPE": "BoxUsage:t3.medium",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "EC2: Running Hours",
        "API_OPERATION": "RunInstances",
        "RESOURCE": "i-0abc1234def567890",
        "AVAILABILITY_ZONE": "ap-south-1a",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services India Private Limited",
        "BILLING_ENTITY": "AWS",
        "COST": 12340
    },
    {
        "ID": 2,
        "BILL_DATE": "2024-12-31T18:30:00.000Z",
        "SERVICE": "Amazon EC2",
        "INSTANCE_TYPE": "t3.large",
        "ACCOUNT_ID": "123456789012",
        "USAGE_TYPE": "BoxUsage:t3.large",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "Reserved",
        "USAGE_TYPE_GROUP": "EC2: Running Hours",
        "API_OPERATION": "StopInstances",
        "RESOURCE": "i-0xyz9876fed543210",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Dedicated",
        "LEGAL_ENTITY": "Amazon Web Services India Private Limited",
        "BILLING_ENTITY": "AWS",
        "COST": 24680
    },
    {
        "ID": 3,
        "BILL_DATE": "2025-01-01T18:30:00.000Z",
        "SERVICE": "Amazon EC2",
        "INSTANCE_TYPE": "t3.small",
        "ACCOUNT_ID": "123456789012",
        "USAGE_TYPE": "BoxUsage:t3.small",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "EC2: Running Hours",
        "API_OPERATION": "RebootInstances",
        "RESOURCE": "i-0111aaaabbbb2222",
        "AVAILABILITY_ZONE": "ap-south-1c",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services India Private Limited",
        "BILLING_ENTITY": "AWS",
        "COST": 37020
    },
    {
        "ID": 4,
        "BILL_DATE": "2025-01-01T18:30:00.000Z",
        "SERVICE": "Amazon EC2",
        "INSTANCE_TYPE": "m5.large",
        "ACCOUNT_ID": "123456789012",
        "USAGE_TYPE": "BoxUsage:m5.large",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "SavingsPlan",
        "USAGE_TYPE_GROUP": "EC2: Running Hours",
        "API_OPERATION": "StartInstances",
        "RESOURCE": "i-0222bbbbcccc3333",
        "AVAILABILITY_ZONE": "ap-south-1a",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services India Private Limited",
        "BILLING_ENTITY": "AWS",
        "COST": 49360
    },
    {
        "ID": 5,
        "BILL_DATE": "2025-01-02T18:30:00.000Z",
        "SERVICE": "Amazon EC2",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "123456789012",
        "USAGE_TYPE": "BoxUsage:c5.large",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "EC2: Running Hours",
        "API_OPERATION": "TerminateInstances",
        "RESOURCE": "i-0333ccccdddd4444",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services India Private Limited",
        "BILLING_ENTITY": "AWS",
        "COST": 61700
    },
    {
        "ID": 6,
        "BILL_DATE": "2024-12-31T18:30:00.000Z",
        "SERVICE": "Amazon S3",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "210987654321",
        "USAGE_TYPE": "TimedStorage-ByteHrs",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "S3: Storage",
        "API_OPERATION": "PutObject",
        "RESOURCE": "my-s3-bucket-1",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 74040
    },
    {
        "ID": 7,
        "BILL_DATE": "2025-01-01T18:30:00.000Z",
        "SERVICE": "Amazon S3",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "210987654321",
        "USAGE_TYPE": "Requests-Tier1",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "S3: Requests",
        "API_OPERATION": "GetObject",
        "RESOURCE": "my-s3-bucket-2",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 86380
    },
    {
        "ID": 8,
        "BILL_DATE": "2025-01-02T18:30:00.000Z",
        "SERVICE": "Amazon S3",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "210987654321",
        "USAGE_TYPE": "Requests-Tier2",
        "PLATFORM": "Linux",
        "REGION": "ap-south-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "S3: Requests",
        "API_OPERATION": "DeleteObject",
        "RESOURCE": "my-s3-bucket-3",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 98720
    },
    {
        "ID": 9,
        "BILL_DATE": "2024-12-31T18:30:00.000Z",
        "SERVICE": "AWS Lambda",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "210987654321",
        "USAGE_TYPE": "Request",
        "PLATFORM": "Linux",
        "REGION": "us-east-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "Lambda: Requests",
        "API_OPERATION": "Invoke",
        "RESOURCE": "lambda-function-1",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 111060
    },
    {
        "ID": 10,
        "BILL_DATE": "2025-01-01T18:30:00.000Z",
        "SERVICE": "AWS Lambda",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "210987654321",
        "USAGE_TYPE": "Request",
        "PLATFORM": "Linux",
        "REGION": "us-east-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "Lambda: Requests",
        "API_OPERATION": "Invoke",
        "RESOURCE": "lambda-function-2",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 123400
    },
    {
        "ID": 11,
        "BILL_DATE": "2025-01-02T18:30:00.000Z",
        "SERVICE": "AWS Lambda",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "210987654321",
        "USAGE_TYPE": "Duration",
        "PLATFORM": "Linux",
        "REGION": "us-east-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "Lambda: Duration",
        "API_OPERATION": "Invoke",
        "RESOURCE": "lambda-function-3",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 135740
    },
    {
        "ID": 12,
        "BILL_DATE": "2024-12-31T18:30:00.000Z",
        "SERVICE": "Amazon DynamoDB",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "345678901234",
        "USAGE_TYPE": "ReadCapacityUnit",
        "PLATFORM": "Linux",
        "REGION": "us-east-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "DynamoDB: Read Capacity",
        "API_OPERATION": "CreateTable",
        "RESOURCE": "dynamodb-table-1",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 148080
    },
    {
        "ID": 13,
        "BILL_DATE": "2025-01-01T18:30:00.000Z",
        "SERVICE": "Amazon DynamoDB",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "345678901234",
        "USAGE_TYPE": "WriteCapacityUnit",
        "PLATFORM": "Linux",
        "REGION": "us-east-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "DynamoDB: Write Capacity",
        "API_OPERATION": "UpdateItem",
        "RESOURCE": "dynamodb-table-2",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 160420
    },
    {
        "ID": 14,
        "BILL_DATE": "2025-01-02T18:30:00.000Z",
        "SERVICE": "Amazon DynamoDB",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "345678901234",
        "USAGE_TYPE": "ReadCapacityUnit",
        "PLATFORM": "Linux",
        "REGION": "us-east-1",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "DynamoDB: Read Capacity",
        "API_OPERATION": "GetItem",
        "RESOURCE": "dynamodb-table-3",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 172760
    },
    {
        "ID": 15,
        "BILL_DATE": "2024-12-31T18:30:00.000Z",
        "SERVICE": "Amazon Redshift",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "456789012345",
        "USAGE_TYPE": "NodeHours",
        "PLATFORM": "Linux",
        "REGION": "us-west-2",
        "PURCHASE_OPTION": "Reserved",
        "USAGE_TYPE_GROUP": "Redshift: Node Hours",
        "API_OPERATION": "CreateCluster",
        "RESOURCE": "redshift-cluster-1",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 185100
    },
    {
        "ID": 16,
        "BILL_DATE": "2025-01-01T18:30:00.000Z",
        "SERVICE": "Amazon Redshift",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "456789012345",
        "USAGE_TYPE": "NodeHours",
        "PLATFORM": "Linux",
        "REGION": "us-west-2",
        "PURCHASE_OPTION": "Reserved",
        "USAGE_TYPE_GROUP": "Redshift: Node Hours",
        "API_OPERATION": "ResizeCluster",
        "RESOURCE": "redshift-cluster-2",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 197440
    },
    {
        "ID": 17,
        "BILL_DATE": "2025-01-02T18:30:00.000Z",
        "SERVICE": "Amazon Redshift",
        "INSTANCE_TYPE": "c5.large",
        "ACCOUNT_ID": "456789012345",
        "USAGE_TYPE": "NodeHours",
        "PLATFORM": "Linux",
        "REGION": "us-west-2",
        "PURCHASE_OPTION": "Reserved",
        "USAGE_TYPE_GROUP": "Redshift: Node Hours",
        "API_OPERATION": "PauseCluster",
        "RESOURCE": "redshift-cluster-3",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 209780
    },
    {
        "ID": 18,
        "BILL_DATE": "2024-12-31T18:30:00.000Z",
        "SERVICE": "Amazon RDS",
        "INSTANCE_TYPE": "db.t3.medium",
        "ACCOUNT_ID": "567890123456",
        "USAGE_TYPE": "InstanceUsage:db.t3.medium",
        "PLATFORM": "MySQL",
        "REGION": "us-east-2",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "RDS: Instance Hours",
        "API_OPERATION": "CreateDBInstance",
        "RESOURCE": "rds-instance-1",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 222120
    },
    {
        "ID": 19,
        "BILL_DATE": "2025-01-01T18:30:00.000Z",
        "SERVICE": "Amazon RDS",
        "INSTANCE_TYPE": "db.t3.large",
        "ACCOUNT_ID": "567890123456",
        "USAGE_TYPE": "InstanceUsage:db.t3.large",
        "PLATFORM": "PostgreSQL",
        "REGION": "us-east-2",
        "PURCHASE_OPTION": "Reserved",
        "USAGE_TYPE_GROUP": "RDS: Instance Hours",
        "API_OPERATION": "ModifyDBInstance",
        "RESOURCE": "rds-instance-2",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 234460
    },
    {
        "ID": 20,
        "BILL_DATE": "2025-01-02T18:30:00.000Z",
        "SERVICE": "Amazon RDS",
        "INSTANCE_TYPE": "db.t3.small",
        "ACCOUNT_ID": "567890123456",
        "USAGE_TYPE": "InstanceUsage:db.t3.small",
        "PLATFORM": "MySQL",
        "REGION": "us-east-2",
        "PURCHASE_OPTION": "OnDemand",
        "USAGE_TYPE_GROUP": "RDS: Instance Hours",
        "API_OPERATION": "DeleteDBInstance",
        "RESOURCE": "rds-instance-3",
        "AVAILABILITY_ZONE": "ap-south-1b",
        "TENANCY": "Shared",
        "LEGAL_ENTITY": "Amazon Web Services Inc.",
        "BILLING_ENTITY": "AWS",
        "COST": 246800
    }]

